//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOtomasyonUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class müsteriKayit
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public Nullable<int> telefonNo { get; set; }
        public string email { get; set; }
    }
}
