//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOtomasyonUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class satisYapilan
    {
        public int id { get; set; }
        public string alıcıAd { get; set; }
        public string alıcıSoyad { get; set; }
        public string alınanÜrün { get; set; }
        public Nullable<int> telefon { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> miktar { get; set; }
    }
}
