//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOtomasyonUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class yetkiliData
    {
        public int tc { get; set; }
        public string yetkiliAdı { get; set; }
        public string yetkiliSoyadı { get; set; }
        public Nullable<int> yetkiliMaası { get; set; }
        public string yetkiliİsBaslangic { get; set; }
        public string yetkiliisBitis { get; set; }
    }
}
